[package]
name = "cspc"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
description = "A C-style policy language for SELinux"

[workspace]

[profile.release]
debug = true

[dependencies]
secsp = { path = "libsecsp" }
symbolic_expressions = "~4.1.9"
clap = "~2.26.0"
