[package]
name = "csp"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]
description = "A C-style policy language for SELinux"

[workspace]

[dependencies]
secsp = { path = "libsecsp" }
